export enum productTypes {
  FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST",
  FETCH_CREATE_PRODUCT_SUCCESS = "FETCH_CREATE_PRODUCT_SUCCESS",
  FETCH_CREATE_PRODUCT_FAILURE = "FETCH_CREATE_PRODUCT_FAILURE",
  FETCH_CREATE_PRODUCT = "FETCH_CREATE_PRODUCT",
  FETCH_GET_PRODUCT_LIST = "FETCH_GET_PRODUCT_LIST",
  GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_FAILURE = "GET_PRODUCT_LIST_FAILURE",
}
